### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by linuxgurugamer** [sea-ex/SmallDebugWindow#2]
The mod works, but I saw this in the log, figured I'd let you know:

[Info   :   BepInEx] Loading [Small Debug Window 0.1.1]
Fallback handler could not load library R:/KSP2_0.1.0/KSP2_x64_Data/Mono/data-0000022D93B10C90.dll

**Comment by sea-ex** [comment]
I appreciate you letting me know! A quick search for the message suggests something more generic to do with Unity, not sure what the implications are. I'll close this issue but please feel free to re-open this issue or open a new one if something stops working.

Thanks for your interest in the mod!
